// LocalActions example — node-local (off-chain) streams via the admin port,
// with optional operator-key authentication.
//
// Local streams live entirely on a single node:
//   - no consensus broadcast, no transaction fees
//   - implicitly owned by the node operator (data_provider is server-derived
//     from the node's secp256k1 key — clients never supply it)
//   - reachable through kwild's admin JSON-RPC server, NOT the gateway
//
// When the node has [extensions.tn_local] require_signature = "true", every
// admin call must carry a signature recovered to the node operator's
// address. Pass the operator key via -operator-key (or set OPERATOR_KEY).
// Without the flag, the SDK works against an unsigned node too — auth is
// opt-in, additive on top of kwild's transport auth.
//
// Flow:
//  1. Connect to the admin server (with or without an operator-key signer)
//  2. (If a key is set) Demonstrate that a wrong key is rejected
//  3. Create a primitive stream, insert 5 records, read them back, query the index
//  4. Create a 2-child composed stream + taxonomy, query the weighted result,
//     then disable the taxonomy to confirm soft-delete
//  5. Confirm the streams appear in list_streams (data_provider is the node's
//     own address, lowercased)
//  6. Clean up everything
//
// Run against a local node spun up with `task single:start:admin` from the node
// repo (admin RPC on http://127.0.0.1:8485). To exercise the auth path, start
// the node with TN_LOCAL_REQUIRE_SIGNATURE=true and pass the operator key:
//
//   # 1. Start the node with auth required
//   TN_LOCAL_REQUIRE_SIGNATURE=true task single:start:admin
//
//   # 2. Pull the autogenerated operator key out of the container
//   OPERATOR_KEY=$(docker exec tn-db cat /root/.kwild/nodekey.json | jq -r '.key')
//
//   # 3. Run the example
//   go run ./examples/local_actions_example/main.go -operator-key=$OPERATOR_KEY
package main

import (
	"context"
	"crypto/ecdsa"
	"flag"
	"fmt"
	"log"
	"os"
	"strings"
	"time"

	"github.com/ethereum/go-ethereum/crypto"
	"github.com/trufnetwork/sdk-go/core/tnclient"
	"github.com/trufnetwork/sdk-go/core/types"
	"github.com/trufnetwork/sdk-go/core/util"
)

const adminURL = "http://127.0.0.1:8485"

func ptr(v int64) *int64 { return &v }

func safeDelete(ctx context.Context, local types.ILocalActions, streamID string) {
	_ = local.DeleteStream(ctx, types.LocalDeleteStreamInput{StreamID: streamID})
}

func generateID(name string) string {
	id := util.GenerateStreamId(name)
	return id.String()
}

// loadOperatorKey reads the operator's secp256k1 private key from the
// -operator-key flag or the OPERATOR_KEY env var. Returns nil if neither
// is set — the example then runs against an unsigned (require_signature=false)
// node.
func loadOperatorKey() *ecdsa.PrivateKey {
	hexKey := flag.String("operator-key", os.Getenv("OPERATOR_KEY"),
		"Operator's secp256k1 private key (hex, no 0x prefix). Required when the node has require_signature=true. "+
			"Pull it from `docker exec tn-db cat /root/.kwild/nodekey.json | jq -r '.key'` for the dev node.")
	flag.Parse()
	if *hexKey == "" {
		return nil
	}
	priv, err := crypto.HexToECDSA(strings.TrimPrefix(*hexKey, "0x"))
	if err != nil {
		log.Fatalf("invalid operator key: %v", err)
	}
	return priv
}

// demonstrateWrongKeyRejection signs requests with a *different* key from
// the node operator's, expecting the server to reject them. This is the
// payoff of the auth feature — proof that admin port reachability alone
// no longer lets a caller act as the operator.
func demonstrateWrongKeyRejection(ctx context.Context) {
	wrongKey, err := crypto.GenerateKey()
	if err != nil {
		log.Fatalf("generate wrong key: %v", err)
	}
	wrongAddr := strings.ToLower(crypto.PubkeyToAddress(wrongKey.PublicKey).Hex())
	fmt.Printf("\n[wrong-key check] signing as %s (NOT the operator)\n", wrongAddr)

	wrongLocal, err := tnclient.NewLocalClientWithSigner(adminURL, wrongKey)
	if err != nil {
		log.Fatalf("construct wrong-key client: %v", err)
	}
	rejectErr := wrongLocal.CreateStream(ctx, types.LocalCreateStreamInput{
		StreamID:   generateID("wrong-key-attempt"),
		StreamType: types.StreamTypePrimitive,
	})
	if rejectErr == nil {
		log.Fatal("  unexpected: server ACCEPTED a wrong-key signed request — auth is broken")
	}
	fmt.Printf("  rejected (expected): %v\n", rejectErr)
}

func main() {
	ctx := context.Background()
	operatorKey := loadOperatorKey()

	var local types.ILocalActions
	var err error
	if operatorKey == nil {
		fmt.Println("no -operator-key set — running unsigned (works only on require_signature=false nodes)")
		local, err = tnclient.NewLocalClient(adminURL)
	} else {
		operatorAddr := strings.ToLower(crypto.PubkeyToAddress(operatorKey.PublicKey).Hex())
		fmt.Printf("signing requests as operator %s\n", operatorAddr)
		local, err = tnclient.NewLocalClientWithSigner(adminURL, operatorKey)
	}
	if err != nil {
		log.Fatalf("connect to admin server: %v", err)
	}
	fmt.Printf("connected to admin server at %s\n", adminURL)

	// If the operator key is configured, prove that a different key is
	// rejected before doing real work — both for confidence and as a
	// runnable example of the property that closes the threat model.
	if operatorKey != nil {
		demonstrateWrongKeyRejection(ctx)
	}

	primitiveID := generateID("local-actions-example-primitive")
	childAID := generateID("local-actions-example-child-a")
	childBID := generateID("local-actions-example-child-b")
	composedID := generateID("local-actions-example-composed")

	for _, sid := range []string{primitiveID, childAID, childBID, composedID} {
		safeDelete(ctx, local, sid)
	}
	defer func() {
		for _, sid := range []string{primitiveID, childAID, childBID, composedID} {
			safeDelete(ctx, local, sid)
		}
		fmt.Println("\ncleanup done.")
	}()

	// ─── Primitive stream ──────────────────────────────────────
	fmt.Printf("\nprimitive stream: %s\n", primitiveID)
	if err := local.CreateStream(ctx, types.LocalCreateStreamInput{
		StreamID:   primitiveID,
		StreamType: types.StreamTypePrimitive,
	}); err != nil {
		log.Fatalf("create primitive: %v", err)
	}

	start := time.Date(2024, 1, 1, 0, 0, 0, 0, time.UTC)
	const numRecords = 5
	streamIDs := make([]string, numRecords)
	eventTimes := make([]int64, numRecords)
	values := make([]string, numRecords)
	for i := 0; i < numRecords; i++ {
		streamIDs[i] = primitiveID
		eventTimes[i] = start.AddDate(0, 0, i).Unix()
		values[i] = fmt.Sprintf("%d", i+1)
	}
	if err := local.InsertRecords(ctx, types.LocalInsertRecordsInput{
		StreamID:  streamIDs,
		EventTime: eventTimes,
		Value:     values,
	}); err != nil {
		log.Fatalf("insert records: %v", err)
	}
	fmt.Printf("  inserted %d records\n", numRecords)

	records, err := local.GetRecord(ctx, types.LocalGetRecordInput{
		StreamID: primitiveID,
		FromTime: ptr(eventTimes[0]),
		ToTime:   ptr(eventTimes[numRecords-1]),
	})
	if err != nil {
		log.Fatalf("get_record: %v", err)
	}
	fmt.Printf("  read back: %d records\n", len(records))
	for _, r := range records[:min(3, len(records))] {
		fmt.Printf("    event_time=%d value=%s\n", r.EventTime, r.Value)
	}

	index, err := local.GetIndex(ctx, types.LocalGetIndexInput{
		StreamID: primitiveID,
		FromTime: ptr(eventTimes[0]),
		ToTime:   ptr(eventTimes[numRecords-1]),
	})
	if err != nil {
		log.Fatalf("get_index: %v", err)
	}
	fmt.Printf("  index[0]=%s, index[-1]=%s\n", index[0].Value, index[len(index)-1].Value)

	// ─── Composed stream + taxonomy ────────────────────────────
	fmt.Printf("\ncomposed stream: %s (children: %s, %s)\n", composedID, childAID, childBID)
	for _, sid := range []string{childAID, childBID} {
		if err := local.CreateStream(ctx, types.LocalCreateStreamInput{
			StreamID: sid, StreamType: types.StreamTypePrimitive,
		}); err != nil {
			log.Fatalf("create child %s: %v", sid, err)
		}
	}
	if err := local.CreateStream(ctx, types.LocalCreateStreamInput{
		StreamID: composedID, StreamType: types.StreamTypeComposed,
	}); err != nil {
		log.Fatalf("create composed: %v", err)
	}

	t := time.Date(2024, 6, 1, 0, 0, 0, 0, time.UTC).Unix()
	if err := local.InsertRecords(ctx, types.LocalInsertRecordsInput{
		StreamID:  []string{childAID, childBID},
		EventTime: []int64{t, t},
		Value:     []string{"100", "200"},
	}); err != nil {
		log.Fatalf("insert child records: %v", err)
	}

	if err := local.InsertTaxonomy(ctx, types.LocalInsertTaxonomyInput{
		StreamID:       composedID,
		ChildStreamIDs: []string{childAID, childBID},
		Weights:        []string{"1", "1"},
		StartDate:      t,
	}); err != nil {
		log.Fatalf("insert_taxonomy: %v", err)
	}

	composedRecords, err := local.GetRecord(ctx, types.LocalGetRecordInput{
		StreamID: composedID, FromTime: ptr(t), ToTime: ptr(t),
	})
	if err != nil {
		log.Fatalf("composed get_record: %v", err)
	}
	fmt.Printf("  composed value at %d: %s (expect ~150)\n", t, composedRecords[0].Value)

	if err := local.DisableTaxonomy(ctx, types.LocalDisableTaxonomyInput{
		StreamID: composedID, GroupSequence: 1,
	}); err != nil {
		log.Fatalf("disable_taxonomy: %v", err)
	}
	afterDisable, err := local.GetRecord(ctx, types.LocalGetRecordInput{
		StreamID: composedID, FromTime: ptr(t), ToTime: ptr(t),
	})
	if err != nil {
		log.Fatalf("composed get_record (after disable): %v", err)
	}
	fmt.Printf("  after disable_taxonomy: %d records (expect 0)\n", len(afterDisable))

	// ─── List streams ──────────────────────────────────────────
	owned := map[string]struct{}{
		primitiveID: {}, childAID: {}, childBID: {}, composedID: {},
	}
	listed, err := local.ListStreams(ctx)
	if err != nil {
		log.Fatalf("list_streams: %v", err)
	}
	var ours []types.LocalStreamInfo
	for _, s := range listed {
		if _, ok := owned[s.StreamID]; ok {
			ours = append(ours, s)
		}
	}
	fmt.Printf("\nlist_streams: %d/%d created streams visible\n", len(ours), len(owned))
	if len(ours) > 0 {
		fmt.Printf("  data_provider: %s (server-derived)\n", ours[0].DataProvider)
	}
}
